# Generated by Django 5.0 on 2024-01-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgqpp', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pdetails', models.CharField(max_length=50)),
                ('cate', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
