# Generated by Django 5.0 on 2024-01-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgqpp', '0007_alter_cart_pid_alter_cart_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='gty',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
