# Generated by Django 5.0 on 2024-01-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgqpp', '0008_cart_gty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='gty',
            new_name='qty',
        ),
    ]
