# Generated by Django 5.0 on 2024-01-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgqpp', '0009_rename_gty_cart_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='qty',
        ),
        migrations.AddField(
            model_name='cart',
            name='qty1',
            field=models.IntegerField(default=1),
        ),
    ]
