# Generated by Django 5.0 on 2024-01-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgqpp', '0012_rename_gty1_cart_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='qty',
            new_name='gty',
        ),
    ]
