# Generated by Django 5.0 on 2024-01-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgqpp', '0014_remove_cart_gty'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='gty',
            field=models.IntegerField(default=1),
        ),
    ]
